In [1]:
#Library - It is a tool which is used to do a specific job. User will give the inputs, the library will do the job for us and will give us the output as well.

In [2]:
# Importing libaries
import numpy as np # Library that contains mathematical tools and will be used to do any mathematics in code
import pandas as pd # Library used for importing datasets and managing them. It's really intuitive as well
import matplotlib.pyplot as plt # pyplot is a sub-library of matplotlib. Used for plotting nice charts.

In [3]:
# Importing the dataset
dataset = pd.read_csv('C:/Users/Admin/Desktop/Python Notebooks/Machine Learning Theory/Machine Learning A-Z/Part 1 - Data Preprocessing/Data.csv')

In [8]:
X = dataset.iloc[:, :-1].values # Used for taking all the rows and all the columns except the last column that's what -1 indicates.
X # In this case X is the independent variable which contains the data for all the independent variables

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [10]:
Y = dataset.iloc[:,-1].values # Used for taking all the rows and only the values of the last column. -1 represents the last column. We could have also used 3 since there are a total of 4 number of columns itself.
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [13]:
#Generally if we have some missing data, then we can replace the missing observation by the mean of all the values in that column.
# Imputer - Imputation transformer for completing missing values.
from sklearn.preprocessing import Imputer 
imputer = Imputer(missing_values = 'NaN',strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:,1:3])
X[:, 1:3] = imputer.transform(X[:,1:3])
X

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [19]:
# Here in the excel file , there are two categorical variables namely country and purchased since they contain categories.
#Encoding categorical data
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0]) # We fit the labelencoder_X object to the first column in the given dataset
X # Now the text is replaced by encoded values, now no more it is having values like France, Germany, Spain they all are replaced by encoded values.
# There is still a problem, even tho ML models r based on numbers, as 2 and 1 r greater than 0, the equations in the model will think that spain has a higher value than germany and france and germany has a higher value than france but that's not the case. It's just 3 categories and there is no relational order between the 3, so comparing them does not make sense. We need to prevent ML model from comparing. In order to stop ML model from comparing, we r going to use dummy variables

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

# Dummy Encoding:
![](capture.png)

In [20]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [21]:
X

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [22]:
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)

In [23]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [26]:
# Splitting the dataset into training and test dataset. It is highly important for the machine to learn from the dataset and derive logical reasoning instead of learning the dataset by heart and not ending up in overtraining. We want the machine to learn from it's past data and form a connection logically so that when the machine get's a new dataset, it will be able to predict. If it ends up in overfitting case, it will not be able to predict for the new dataset since it will learn everything by heart and will not be able to perform optimally on a new dataset. 
# Traininig set is the one on which the model learns and the test set on which we test if the machine learning model correctly learnt the correaltions.
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [31]:
# Feature Scaling- When variables in the dataset do not have the same scale it will cause issues. That's mainly because a lot of machine learning models are based on euclidian distance.
# We are essentially putting variables in the same scale and the same range so that no variable is dominated by the other.
# There are two types of feature scaling - Normalisation and Standardisation
# For the ML models which are not based on euclidian distance, we still need to do feature scaling for example in case of decision trees which are not based on euclidian distance, we will do feature scaling because this will improve the speed and if feature scaling is not done, then the model will run for a very long time.
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test) # For test set we do not need to fix the object to the test set since it's already fit to the training set.

In [32]:
# Feature scaling on X_train and X_test is the same since the same standardscaler object is fit to X_train. That's why we fit the standardscaler object to X_train.
# We do not need to apply feature scaling on Y in this dataset since it is a classification problem. In case of regression, when the dependent variable will take a huge range of values, we will need to apply feature scaling to the dependent variable Y as well.