## Data

We will be using articles from NPR (National Public Radio), obtained from their website [www.npr.org](http://www.npr.org)

In [2]:
import pandas as pd

In [3]:
npr = pd.read_csv('npr.csv')

In [4]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [5]:
npr['Article'][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [6]:
len(npr)

11992

In [7]:
npr['Article'][4001]

'In 2010, Sonia Vallabh watched her mom, Kamni Vallabh, die in a really horrible way. First, her mom’s memory started to go, then she lost the ability to reason. Sonia says it was like watching someone get unplugged from the world. By the end, it was as if she was stuck between being awake and asleep. She was confused and uncomfortable all the time. ”Even when awake, was she fully or was she really? And when asleep, was she really asleep?” says Sonia. The smart, warm, artistic Kamni  —   just 51 years old  —   was disappearing into profound dementia. ”I think until you’ve seen it, it’s hard to actually imagine what it is for a person to be alive and their body is moving around, but their brain is not there anymore,” says Eric Minikel, Sonia’s husband. In less than a year, Sonia’s mom died. An autopsy showed Kamni had died from something rare  —   a prion disease. Specifically, one called fatal familial insomnia because in some patients it steals the ability to fall asleep. Basically, c

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
# max_df is used for when we are building up the vocab we will generally ignore certain terms that have really high document frequency. This essentially get's rid of terms that are really common across a lot of documents.
# min_df is used to indicate minimum document frequency, the words that show up a minimum amount of times
cv = CountVectorizer(max_df=0.9,min_df=2,stop_words='english')

We are not going to do any train-test split since this is unsupervised learning. We do not have any label to test against therefore it does not make any sense to do train test split

**`max_df`**` : float in range [0.0, 1.0] or int, default=1.0`<br>
When building the vocabulary ignore terms that have a document frequency strictly higher than the given threshold (corpus-specific stop words). If float, the parameter represents a proportion of documents, integer absolute counts. This parameter is ignored if vocabulary is not None.

**`min_df`**` : float in range [0.0, 1.0] or int, default=1`<br>
When building the vocabulary ignore terms that have a document frequency strictly lower than the given threshold. This value is also called cut-off in the literature. If float, the parameter represents a proportion of documents, integer absolute counts. This parameter is ignored if vocabulary is not None.

In [11]:
dtm = cv.fit_transform(npr['Article'])

In [12]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [13]:
from sklearn.decomposition import LatentDirichletAllocation

In [14]:
LDA = LatentDirichletAllocation(n_components=7,random_state = 42)

In [15]:
LDA.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=7, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

## Showing Stored Words

In [16]:
# Grabbing the vocabulary of words
len(cv.get_feature_names())

54777

In [17]:
type(cv.get_feature_names())

list

In [20]:
cv.get_feature_names()[31000]

'menagerie'

In [30]:
import random
import numpy as np
random_word_id = random.randint(0,54777)
cv.get_feature_names()[random_word_id]

'john'

### Showing Top Words Per Topic

In [24]:
# Grabbing the topics
len(LDA.components_)

7

In [25]:
type(LDA.components_)

numpy.ndarray

In [26]:
LDA.components_.shape

(7, 54777)

In [27]:
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [28]:
single_topic = LDA.components_[0]
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [31]:
arr = np.array([10,200,1])

In [32]:
arr.argsort()

array([2, 0, 1], dtype=int64)

In [33]:
# ARGSORT ---> INDEX POSITIONS SORTED FROM LEAST ---> GREATEST 
# WE WANT TOP 10 VALUES(10 GREATEST VALUES)
# LAST 10 VALUES OF ARGSORT()
single_topic.argsort()[-10:] # grabs the last 10 values of .argsort()

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [37]:
top_twenty_words = single_topic.argsort()[-20:]

In [38]:
for index in top_twenty_words:
    print(cv.get_feature_names()[index])

president
state
tax
insurance
trump
companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says


In [41]:
# Grabbing the highest probabilty words per topic
for index,topic in enumerate(LDA.components_):
    print(f"THE TOP 15 WORDS FOR THE TOPIC #{index+1}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    

THE TOP 15 WORDS FOR THE TOPIC #1
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']
THE TOP 15 WORDS FOR THE TOPIC #2
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']
THE TOP 15 WORDS FOR THE TOPIC #3
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']
THE TOP 15 WORDS FOR THE TOPIC #4
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']
THE TOP 15 WORDS FOR THE TOPIC #5
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']
THE TOP 15 WORDS FOR THE TOPIC #6
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'k

In [42]:
dtm 

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [43]:
npr

Article
0      In the Washington of 2016, even when the polic...
1        Donald Trump has used Twitter  —   his prefe...
2        Donald Trump is unabashedly praising Russian...
3      Updated at 2:50 p. m. ET, Russian President Vl...
4      From photography, illustration and video, to d...
...                                                  ...
11987  The number of law enforcement officers shot an...
11988    Trump is busy these days with victory tours,...
11989  It’s always interesting for the Goats and Soda...
11990  The election of Donald Trump was a surprise to...
11991  Voters in the English city of Sunderland did s...

[11992 rows x 1 columns]

In [44]:
topic_results = LDA.transform(dtm)

In [45]:
topic_results.shape

(11992, 7)

In [46]:
topic_results[0]

array([1.61040465e-02, 6.83341493e-01, 2.25376318e-04, 2.25369288e-04,
       2.99652737e-01, 2.25479379e-04, 2.25497980e-04])

In [47]:
topic_results[0].argmax()

1

### Combining with Original Data

In [49]:
npr['Topic'] = topic_results.argmax(axis=1)

In [50]:
npr

Article  Topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      2
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      1
11988    Trump is busy these days with victory tours,...      4
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      0

[11992 rows x 2 columns]